version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: digitaltwins-minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_storage:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    networks:
      - digitaltwins-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: digitaltwins-qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - digitaltwins-network

  api:
    build: .
    image: digitaltwins-api:latest
    container_name: digitaltwins-api
    ports:
      - "8000:8000"
    environment:
      - APP_NAME="DATHA Marketplace"
      - APP_DESCRIPTION="DATHA Marketplace API for searching and retrieving catalog items."
      - EMBEDDING_MODEL_NAME=jinaai/jina-embeddings-v3
      - LANGUAGE_MODEL_NAME=meta-llama/Llama-3.1-8B-Instruct
      - HUGGINGFACE_API_TOKEN=YOUR_TOKEN
      - DEVICE=auto
      - EMBEDDING_DEVICE=auto
      - LLM_DEVICE=auto
      - DEFAULT_TOP_K=5
      - PROMPT_TEMPLATE="As an intelligent language model, your role is to accurately determine whether the provided data is relevant to the user's query. Answer ONLY with 'Yes' or 'No'"
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_SECURE=false
      - MINIO_DATASETS_BUCKET=datasets
      - MINIO_MODELS_BUCKET=models
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_USE_HTTP=false
      - QDRANT_DATASETS_COLLECTION=datasets
      - QDRANT_MODELS_COLLECTION=models
      - VECTOR_SIZE=1024
    depends_on:
      - minio
      - qdrant
    networks:
      - digitaltwins-network

volumes:
  minio_storage:
  qdrant_storage:

networks:
  digitaltwins-network:
    driver: bridge
