# FastApi Route Tests

@baseUrl = http://127.0.0.1:8000
@model_id = binwang/RSE-BERT-base-STS
@dataset_id = nbroad/mediasum


### Root
GET {{baseUrl}}/
Accept: text/html

### Sample Datasets
GET {{baseUrl}}/datasets

### Api Datasets
GET {{baseUrl}}/api/datasets


### Api Models
GET {{baseUrl}}/api/models

### Add a new dataset item
POST http://127.0.0.1:8000/datasets/add
Content-Type: application/x-www-form-urlencoded
Accept: application/json

dataset_id = my-new-dataset-diego

### Search datasets
POST {{baseUrl}}/search/datasets
Content-Type: application/x-www-form-urlencoded
Accept: application/json

description = sentiment analysis

### Download dataset file
GET {{baseUrl}}/datasets/{{dataset_id}}/data
Accept: text/plain


### Sample Models
GET {{baseUrl}}/models

### Add a new model item
POST http://127.0.0.1:8000/models/add
Content-Type: application/x-www-form-urlencoded
Accept: application/json

model_id = my-new-model-diego

### Search models
POST {{baseUrl}}/search/models
Content-Type: application/x-www-form-urlencoded
Accept: application/json

description = text classification

### Download model file
GET {{baseUrl}}/models/facebook/fasttext-no-vectors/weights


### Api Search for models
POST {{baseUrl}}/api/search/models
Content-Type: application/x-www-form-urlencoded
Accept: application/json

description = text classification

### Api Search for datasets
POST {{baseUrl}}/api/search/datasets
Content-Type: application/x-www-form-urlencoded
Accept: application/json

description = sentiment analysis

### Delete a dataset item
DELETE {{baseUrl}}/api/datasets/{{dataset_id}}
Accept: application/json

### Delete a model item
DELETE {{baseUrl}}/api/models/{{model_id}}
Accept: application/json